# Configuration for tuning of the collider
config_collider:
  config_knobs_and_tuning:
    knob_settings:
      # Orbit knobs
      on_x1: 170 # [urad]
      on_sep1: 1e-3 # [mm]
      on_x2v: -170 # [urad]
      on_sep2h: 1e-3 # [mm]
      on_sep2v: 0 # [mm]
      on_x5: 170 # [urad]
      on_sep5: 1e-3 # [mm]
      on_x8h: -170 # [urad]
      on_sep8h: 0 # [mm]
      on_sep8v: 1e-10 # [mm]
      on_ov2: 0 # [mm]
      on_ov5: 0 # [mm]

      # Spurious dispersion correction
      on_disp: 1.000 # Value to choose could be optics-dependent

      # Magnets of the experiments
      on_alice_normalized: 1
      on_lhcb_normalized: -1
      on_sol_atlas: 0
      on_sol_cms: 0
      on_sol_alice: 0

      # RF voltage and phases
      vrf400: 1148 # [MV]
      lagrf400.b1: 0.5 # [rad]
      lagrf400.b2: 0. # [rad]

      # Octupoles
      i_oct_b1: 100. # [A]
      i_oct_b2: 100. # [A]

    closed_orbit_correction:
      lhcb1: correction/corr_co_lhcb1.json
      lhcb2: correction/corr_co_lhcb2.json

    # Tunes and chromaticities
    qx:
      lhcb1: 62.31
      lhcb2: 62.31
    qy:
      lhcb1: 60.32
      lhcb2: 60.32
    dqx:
      lhcb1: 10.0
      lhcb2: 10.0
    dqy:
      lhcb1: 10.0
      lhcb2: 10.0

    # Linear coupling
    delta_cmr: 0.0
    delta_cmi: 0.0

    knob_names:
      lhcb1:
        q_knob_1: dqx.b1_sq
        q_knob_2: dqy.b1_sq
        dq_knob_1: dqpx.b1_sq
        dq_knob_2: dqpy.b1_sq
        c_minus_knob_1: cmrs.b1_sq
        c_minus_knob_2: cmis.b1_sq
        # ! Warning, maybe the knobs below are correct
        # c_minus_knob_1: c_minus_re_b1
        # c_minus_knob_2: c_minus_im_b1
      lhcb2:
        q_knob_1: dqx.b2_sq
        q_knob_2: dqy.b2_sq
        dq_knob_1: dqpx.b2_sq
        dq_knob_2: dqpy.b2_sq
        c_minus_knob_1: cmrs.b2_sq
        c_minus_knob_2: cmis.b2_sq
        # ! Same
        # c_minus_knob_1: c_minus_re_b2
        # c_minus_knob_2: c_minus_im_b2

  config_beambeam:
    skip_beambeam: false
    bunch_spacing_buckets: 10
    num_slices_head_on: 11
    num_long_range_encounters_per_side:
      ip1: 10
      ip2: 9
      ip5: 10
      ip8: 9
    sigma_z: 0.0824
    num_particles_per_bunch: 180000000.0
    nemitt_x: 1.65e-6
    nemitt_y: 1.65e-6
    mask_with_filling_pattern:
      pattern_fname: ../../filling_scheme/50ns_1240b_1088_1088_398_56bpi_PbPb_converted.json
      i_bunch_b1: 480 # If not specified, the bunch with the worst schedule is chosen
      i_bunch_b2: 1363 # Same. A value for i_bunch_b1 and i_bunch_b2 must be specified if pattern_fname is specified

  skip_leveling: false
  config_lumi_leveling:
    ip1:
      luminosity: 6.4e+27
      num_colliding_bunches:
      impose_separation_orthogonal_to_crossing: false
      knobs:
        - on_sep1
      bump_range:
        lhcb1:
          - e.ds.l1.b1
          - s.ds.r1.b1
        lhcb2:
          - s.ds.r1.b2
          - e.ds.l1.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        - corr_co_acbyvs4.l1b1
        - corr_co_acbyhs4.l1b1
        - corr_co_acbyvs4.r1b2
        - corr_co_acbyhs4.r1b2
        - corr_co_acbyhs4.r1b1
        - corr_co_acbyvs4.r1b1
        - corr_co_acbyhs4.l1b2
        - corr_co_acbyvs4.l1b2
        - corr_co_acbcv5.l1b1
        - corr_co_acbch5.r1b1
        - corr_co_acbcv5.r1b2
        - corr_co_acbch5.l1b2

    ip5:
      luminosity: 6.4e+27
      num_colliding_bunches:
      impose_separation_orthogonal_to_crossing: false
      knobs:
        - on_sep5
      bump_range:
        lhcb1:
          - e.ds.l5.b1
          - s.ds.r5.b1
        lhcb2:
          - s.ds.r5.b2
          - e.ds.l5.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        - corr_co_acbcv5.l5b1
        - corr_co_acbch5.r5b1
        - corr_co_acbyhs4.l5b1
        - corr_co_acbyhs4.r5b1
        - corr_co_acbyvs4.l5b1
        - corr_co_acbyvs4.r5b1
        - corr_co_acbcv5.r5b2
        - corr_co_acbch5.l5b2
        - corr_co_acbyhs4.l5b2
        - corr_co_acbyhs4.r5b2
        - corr_co_acbyvs4.l5b2
        - corr_co_acbyvs4.r5b2

    ip2:
      luminosity: 6.4e+27
      num_colliding_bunches:
      impose_separation_orthogonal_to_crossing: false
      knobs:
        - on_sep2h
      bump_range:
        lhcb1:
          - e.ds.l2.b1
          - s.ds.r2.b1
        lhcb2:
          - s.ds.r2.b2
          - e.ds.l2.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
        - corr_co_acbyvs4.l2b1
        - corr_co_acbyhs4.l2b1
        - corr_co_acbyvs4.r2b2
        - corr_co_acbyhs4.r2b2
          # to close the bumps
        - corr_co_acbyvs4.l2b2
        - corr_co_acbyhs4.l2b2
        - corr_co_acbyvs4.r2b1
        - corr_co_acbyhs4.r2b1
        - corr_co_acbyhs5.l2b2
        - corr_co_acbyvs5.l2b2
        - corr_co_acbchs5.r2b1
        - corr_co_acbcvs5.r2b1

    ip8:
      luminosity: 1.0e+27
      num_colliding_bunches:
      impose_separation_orthogonal_to_crossing: false
      knobs:
        - on_sep8v
      bump_range:
        lhcb1:
          - e.ds.l8.b1
          - s.ds.r8.b1
        lhcb2:
          - s.ds.r8.b2
          - e.ds.l8.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
        - corr_co_acbyvs4.l8b1
        - corr_co_acbyhs4.l8b1
        - corr_co_acbyvs4.r8b2
        - corr_co_acbyhs4.r8b2
          # to close the bumps
        - corr_co_acbyvs4.l8b2
        - corr_co_acbyhs4.l8b2
        - corr_co_acbyvs4.r8b1
        - corr_co_acbyhs4.r8b1
        - corr_co_acbcvs5.l8b2
        - corr_co_acbchs5.l8b2
        - corr_co_acbyvs5.r8b1
        - corr_co_acbyhs5.r8b1

config_simulation:
  # Collider file
  collider_file: ../1_build_distr_and_collider/collider/collider.json

  # Distribution in the normalized xy space
  particle_file: ../1_build_distr_and_collider/particles/00.parquet

  # Initial off-momentum
  delta_max: 0.00024

  # Tracking
  n_turns: 1000 # number of turns to track

  # Beam to track
  beam: "lhcb1" #lhcb1 or lhcb2

# Save collider or not
dump_collider: false
dump_config_in_collider: false

# Context for the simulation
context: "cpu" # 'cupy' # opencl

# Log
log_file: tree_maker.log
